# Generated by Django 2.0 on 2019-04-05 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import members.user_manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('extra_can_read_task', 'Can read tasks'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=30, verbose_name='firstName')),
                ('display_name', models.CharField(max_length=30, verbose_name='displayName')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='lastName')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='dateJoined')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('status', models.PositiveIntegerField(choices=[(1, 'working'), (0, 'blocked'), (2, 'deleted'), (3, 'unverified')], default=1)),
                ('lang', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('kin', 'Kiniyiwrwanda')], default='en', max_length=6, verbose_name='language')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', members.user_manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='taskName')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
